// Code generated by "stringer -type=installState"; DO NOT EDIT.

package state

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[NotInstalled-1]
	_ = x[PlistPresentButNotLoaded-2]
	_ = x[Installed-3]
}

const _installState_name = "UnknownNotInstalledPlistPresentButNotLoadedInstalled"

var _installState_index = [...]uint8{0, 7, 19, 43, 52}

func (i installState) String() string {
	if i < 0 || i >= installState(len(_installState_index)-1) {
		return "installState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _installState_name[_installState_index[i]:_installState_index[i+1]]
}
