// Code generated by "stringer -type=runState"; DO NOT EDIT.

package state

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unknownRS-0]
	_ = x[NoSuchService-1]
	_ = x[Running-2]
	_ = x[Starting-3]
	_ = x[NotRunning-4]
}

const _runState_name = "unknownRSNoSuchServiceRunningStartingNotRunning"

var _runState_index = [...]uint8{0, 9, 22, 29, 37, 47}

func (i runState) String() string {
	if i < 0 || i >= runState(len(_runState_index)-1) {
		return "runState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _runState_name[_runState_index[i]:_runState_index[i+1]]
}
